source 'http://ruby.taobao.org'

gem 'rake'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-synchrony', :require => 'sinatra/synchrony'
gem 'em-synchrony', '1.0.3', :require => ['em-synchrony', 'em-synchrony/mysql2', 'em-synchrony/activerecord']
gem 'activerecord', :require => 'active_record'
# gem 'sinatra-activerecord'
gem 'mysql2'
gem 'racksh'

gem 'thin'

gem 'slim'
gem 'tilt-jbuilder', :require => "sinatra/jbuilder"
gem 'rack_csrf', :require => "rack/csrf"

group :development do
  gem 'shotgun'
end