require 'yaml'
require 'sinatra/activerecord'
require "sinatra/activerecord/rake"

db_conf = YAML.load_file(File.expand_path('../config/database.yml', __FILE__))
ActiveRecord::Tasks::DatabaseTasks.database_configuration = db_conf

# need `gem uninstall bigdecimal` to ignore warning!!