source 'http://ruby.taobao.org'

gem 'goliath', :require => false # https://github.com/postrank-labs/goliath/issues/265
gem 'grape'
gem 'grape-jbuilder'

gem 'mysql2'
gem 'em-synchrony', '1.0.3', :require => ['em-synchrony', 'em-synchrony/mysql2', 'em-synchrony/activerecord']
gem 'rack-fiber_pool',  :require => 'rack/fiber_pool'
gem 'activerecord', :require => 'active_record'

gem 'settingslogic'

group :development do
  gem 'mina'
end